INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Ação Civil Coletiva', 63);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Demarcação / Divisão', 34);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Depósito', 35);  
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Despejo', 92);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Despejo por Falta de Pagamento', 93);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Execução de Título Extrajudicial', 159);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Mandado de Segurança', 120);
INSERT INTO 'TbClasse' ('classe','idClasse') VALUES ('Mandado de Segurança Coletivo', 119);

INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Abatimento proporcional do preço', 7769, 63);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Acidente Aéreo', 7748, 63);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Assinatura Básica Mensal', 7626, 63);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Atraso de vôo', 4829, 63);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Bancários', 7752, 63);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Alteração de Coisa Comum', 10465, 34);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Divisão e Demarcação', 10451, 34);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Alienação Fiduciária', 9582, 35);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Despejo para Uso de Ascendentes e Descendentes', 9611, 92);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Inadimplemento', 7691, 93);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Alienação Fiduciária', 958, 159);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Alienação Judicial', 10454, 159);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Cheque', 4970, 159);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Compra e Venda', 9587, 159);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Contratos Bancário's, 9607, 159);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Fornecimento de Água', 7761, 120);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Fornecimento de Energia Elétrica', 7760, 120);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Planos de Saúde', 6233, 120);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Estabelecimentos de Ensino', 7620, 119);
INSERT INTO 'TbAssuntoPrincipal' ('TbAssuntoPrincipal', 'idAssuntoPrincipal', 'idClasse') VALUES ('Planos de Saúde', 6233, 119);

INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Responsabilidade do Fornecedor', 6220);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Transporte Aéreo', 4862);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Telefonia', 7617);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Contratos de Consumo', 7771);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Condomínio em Edifício', 10463);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Propriedade', 10448);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Espécies de Contratos', 9580);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Locação de Imóvel', 9593);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Obrigações', 7681);
INSERT INTO 'TbAssuntoGenerico' ('AssuntoGenerico', 'idAssuntoGenerico') VALUES ('Espécies de Títulos de Crédito', 7717);

INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (1,7769,6220);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (2,7748,4862);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (3,7626,7617);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (4,4829,4862);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (5,7752,7771);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (6,10465,10463);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (7,10451,10448);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (8,9582,9580);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (9,9611,9593);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (10,7691,7681);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (11,9582,9580);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (12,10454,10448);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (13,4970,7717);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (14,9587,9580);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (15,9607,9580);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (16,7761,7771);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (17,7760,7771);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (18,6233,7771);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (19,7620,7771);
INSERT INTO 'TbAssuntoPrincipalGenerico' ('idAssuntoPrincipalGenerico'. 'idAssuntoPrincipal', 'idAssuntoGenerico') VALUES (20,6233,7771);


